export const SET_POKE_GENERATION_NO = 'SET_POKE_GENERATION_NO';
export const SET_LEFT_POKE = 'SET_LEFT_POKE';
export const SET_RIGHT_POKE = 'SET_RIGHT_POKE';
export const CHANGE_CARD_SIDE = 'CHANGE_CARD_SIDE';
